syntax = "proto3";

package meshtastic;

import "nanopb.proto";

message CrisislabMessage {
	message Empty {}

	message SignalData {
		message Entry {
			uint32 sending_node_id = 1;
			int32 rssi = 2;
			float snr = 3;
		}

		uint32 receiving_node_id = 1;

		repeated Entry signal_entries = 2 [(nanopb).max_count = 10];
	}

	oneof message {
		uint32 broadcast_interval_seconds = 1;
		string channel_name = 2 [(nanopb).max_length = 11];
		Empty update_routes = 3;
		uint64 ping_timestamp = 4;
		SignalData signal_data = 5;
	}
}
