syntax = "proto3";

package meshtastic;

import "nanopb.proto";
import "meshtastic/mesh.proto";
import "meshtastic/telemetry.proto";

message CrisislabMessage {
	message SignalData {
		message Entry {
			uint32 from = 1; // node id
			int32 rssi = 2;
			float snr = 3;
		}

		uint32 to = 1; // node id
		bool is_gateway = 2;
		repeated Entry links = 3;
	}

	message MeshSettings {
		optional uint32 broadcast_interval_seconds = 1;
		optional string channel_name = 2;
		optional uint32 ping_timeout_seconds = 3;
	}

	message ServerSettings {
		optional uint32 signal_data_timeout_seconds = 1;
	}

	message Empty {}

	message NextHops {
		repeated uint32 node_ids = 1;
	}

	message NextHopsMap {
		map<uint32, NextHops> entries = 1;
	}

	message LiveData {
		uint32 node_num = 1;
		uint64 timestamp = 2; // seconds since unix epoch
		User user = 3;
		Position position = 4;
		DeviceMetrics device_metrics = 5;
	}

	oneof message {
		MeshSettings mesh_settings = 1;
		Empty get_mesh_settings_request = 2;
		ServerSettings server_settings = 3;
		Empty update_next_hops_request = 4;
		uint64 ping_timestamp = 5; // seconds since unix epoch
		SignalData signal_data = 6;
		NextHopsMap updated_next_hops = 7;
		Empty start_live_data = 8;
		Empty stop_live_data = 9;
		LiveData live_data = 10;
	}
}
